### PR TITLE
some advanced_settings are required

### PR DESCRIPTION
**Pull request by cinek810**
without those set replication doesn't work as expected. I gathered some errors here: https://funinit.wordpress.com/#irepl-errors

### CODE REVIEW

**Comment by trel** [comment]
very good - thanks.    this will be included before we roll out 4.3.0, definitely.    if we work out the backport, we could make version 4 required for the 4.2.x series as well.

**Comment by cinek810** [comment]
@trel what do you mean by backport - is it something I can help with?

**Comment by trel** [comment]
We'll include this fix in the main repository, rather than here, as v4.  And we'd need to make the same changes both for the master branch (which will become 4.3.0) and the 4-2-stable branch (from which 4.2.x is released).

I expect the newly-marked required elements will need to get into:
- the schema itself
- the upgrade mechanism (when the server starts after a new package is installed)
- the izonereport
- the default installation/template
- the docs

**Comment by cinek810** [comment]
OK.. I can submit changes from both PRs I opened here to one in irods/irods. From what I checked it looks like it's already fine in:
- izonereport (attributes are returned there)
- installation/template (if you mean ```server_config.json``` in ```packaging``` directory
Can you point me to a places to check for:
 - upgrade mechanism
 - docs?
Do you mean that it should all go to ```configuration_schemas/v4```? I don't know the approach you have, but since it's really not changing configuration schema but just fixing validation shouldn't it still be ```v3``` ?

**Comment by trel** [comment]
@korydraughn also please look at this one...

this is the last open PR, then we can archive this repository (functionality has been included in irods/irods proper now).

**Comment by korydraughn** [comment]
This is being handled in irods/irods.

See https://github.com/irods/irods/pull/6316

The PR doesn't handle `izonereport`. That can be handled in a separate PR in irods/irods.

**Comment by trel** [comment]
got it - thanks.   closing here.

**Pull request closed without merging**
